services:
  postgres16:
    container_name: 'postgres16-zerotoprod'
    image: postgres:16-alpine
    ports: 
      - '127.0.0.1:5432:5432'
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD